apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: courses
  environment: dev
  app: courses
  version: v1
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: courses.192.168.99.100.nip.io
    http:
      paths:
      - backend:
          serviceName: courses
          servicePort: 80