apiVersion: v1
kind: Service
metadata:
  name: courses
  labels:
    name: courses
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30001
    name: http
  selector:
    name: courses
    environment: dev
