apiVersion: v1
kind: Service
metadata:
  name: courses
  labels:
    name: courses
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    name: courses
    environment: dev
