apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    name: mongo
    environment: dev
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        name: mongo
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
            - name: MONGODB_DATABASE
              value: university
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
